"""add relationship

Revision ID: 8ad5c88dbb4e
Revises: 68a872d5103d
Create Date: 2025-01-07 18:08:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8ad5c88dbb4e'
down_revision = '3a86d9360baf'
branch_labels = None
depends_on = None


# 升级函数，向todo表添加用户外键列和约束
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 第一步：添加可空的 user_id 列
    op.add_column('todo', sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    
    # 第二步：为现有数据设置 user_id（使用第一个用户的 id）
    connection = op.get_bind()
    # 获取第一个用户的 id
    result = connection.execute(sa.text("SELECT id FROM \"user\" LIMIT 1"))
    first_user = result.fetchone()
    if first_user:
        # 更新所有 user_id 为空的 todo 记录
        connection.execute(
            sa.text("UPDATE todo SET user_id = :user_id WHERE user_id IS NULL"),
            {"user_id": first_user[0]}
        )
    
    # 第三步：将 user_id 列改为非空
    op.alter_column('todo', 'user_id', nullable=False)
    
    # 创建外键约束
    op.create_foreign_key('fk_todo_user_id_user', 'todo', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


# 回滚函数，移除新增的外键列和约束
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_todo_user_id_user', 'todo', type_='foreignkey')
    op.drop_column('todo', 'user_id')
    # ### end Alembic commands ###
